import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Post from '../components/Post'
import PostForm from '../components/PostForm'
import Bio from '../components/Bio'
import { useAuth } from '../hooks/useAuth'

export default function Home() {
  const { user, logIn, logOut } = useAuth()

  console.log(user)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      { !user && (
        <p>
          <button onClick={logIn}>Log In</button>
        </p>
      )}

      { user && (
        <p>
          <button onClick={logOut}>Log Out</button>
        </p>
      )}

      <main className={styles.main}>

        <Bio 
          headshot='https://images.unsplash.com/photo-1574047473179-a73921fc1eb6?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c3RhciUyMHdhcnN8ZW58MHwyfDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60'
          name='Finn'
          tagline='Help me, Obi-Wan Kenobi. You’re my only hope.'
          role='Clone Trooper' 
        />

        <ul className={styles.post}>
          <li>
            <Post 
              content='I find your lack of faith disturbing.' 
              date='4/4/2015' 
            />
          </li>
          <li>
           <Post 
            content='It’s the ship that made the Kessel run in less than twelve parsecs. I’ve outrun Imperial starships. Not the local bulk cruisers, mind you. I’m talking about the big Corellian ships, now. She’s fast enough for you, old man.' 
            date='4/4/2015' 
           />
          </li>
          <li>
            <Post 
              content='Fear is the path to the dark side. Fear leads to anger; anger leads to hate; hate leads to suffering. I sense much fear in you.' 
              date='4/4/2015' 
            />
          </li>
        </ul>

        { user && (
          <PostForm />
        )}

      </main>
    </div>
  )
}
